from xcc.aot.analysis import AotAnalysis, analyze_path, analyze_source
from xcc.aot.binder import bind_types
from xcc.aot.bootstrap import (
    AotBootstrapAdmissionReport,
    AotBootstrapEntryPlan,
    build_native_bootstrap,
    collect_bootstrap_sources,
    lower_bootstrap_entry_smoke,
    plan_bootstrap_entry,
    summarize_bootstrap_admission,
)
from xcc.aot.diag import AotDiagnostic, AotError
from xcc.aot.ir import (
    IrAssign,
    IrBinary,
    IrBoolType,
    IrBranch,
    IrCall,
    IrConstBool,
    IrConstInt,
    IrConstNone,
    IrConstructRecord,
    IrConstString,
    IrExpr,
    IrField,
    IrForEach,
    IrFunction,
    IrGetField,
    IrIf,
    IrIntType,
    IrModule,
    IrName,
    IrNoneType,
    IrParam,
    IrPrint,
    IrRaise,
    IrRecord,
    IrRecordType,
    IrReturn,
    IrStmt,
    IrStringConcat,
    IrStringJoin,
    IrStringType,
    IrTuple,
    IrTupleSlice,
    IrTupleType,
    IrType,
)
from xcc.aot.llvm_text import emit_llvm_text
from xcc.aot.lower import lower_source_to_ir
from xcc.aot.module import AotModule, parse_path, parse_source
from xcc.aot.native import (
    NativeSmokeResult,
    compile_llvm_executable,
    run_native_core_smoke,
    run_native_smoke,
)
from xcc.aot.slice import (
    AotSliceInput,
    collect_slice_inputs,
    core_entry_wrapper,
    core_slice_entry_module,
    lower_core_entry_slice,
    lower_core_slice,
)
from xcc.aot.subset import AotModuleSummary, check_subset
from xcc.aot.types import AotClassInfo, AotFunctionInfo, AotType, AotTypeAnalysis

__all__ = (
    "AotAnalysis",
    "AotBootstrapAdmissionReport",
    "AotBootstrapEntryPlan",
    "AotClassInfo",
    "AotDiagnostic",
    "AotError",
    "AotFunctionInfo",
    "AotModule",
    "AotModuleSummary",
    "AotSliceInput",
    "AotType",
    "AotTypeAnalysis",
    "IrAssign",
    "IrBinary",
    "IrBoolType",
    "IrBranch",
    "IrCall",
    "IrConstBool",
    "IrConstInt",
    "IrConstNone",
    "IrConstString",
    "IrConstructRecord",
    "IrExpr",
    "IrField",
    "IrForEach",
    "IrFunction",
    "IrGetField",
    "IrIf",
    "IrIntType",
    "IrModule",
    "IrName",
    "IrNoneType",
    "IrParam",
    "IrPrint",
    "IrRaise",
    "IrRecord",
    "IrRecordType",
    "IrReturn",
    "IrStmt",
    "IrStringConcat",
    "IrStringJoin",
    "IrStringType",
    "IrTuple",
    "IrTupleSlice",
    "IrTupleType",
    "IrType",
    "NativeSmokeResult",
    "analyze_path",
    "analyze_source",
    "bind_types",
    "check_subset",
    "build_native_bootstrap",
    "compile_llvm_executable",
    "collect_bootstrap_sources",
    "collect_slice_inputs",
    "core_entry_wrapper",
    "lower_core_entry_slice",
    "core_slice_entry_module",
    "emit_llvm_text",
    "lower_core_slice",
    "lower_bootstrap_entry_smoke",
    "lower_source_to_ir",
    "parse_path",
    "parse_source",
    "plan_bootstrap_entry",
    "run_native_core_smoke",
    "run_native_smoke",
    "summarize_bootstrap_admission",
)
