def runtime_prelude() -> str:
    return "\n".join(
        (
            '@__xcc_aot_fmt_i64 = private unnamed_addr constant [5 x i8] c"%lld\\00", align 1',
            "",
            "declare i32 @puts(ptr)",
            "declare ptr @malloc(i64)",
            "declare i64 @strlen(ptr)",
            "declare ptr @memcpy(ptr, ptr, i64)",
            "declare i32 @strcmp(ptr, ptr)",
            "declare i32 @snprintf(ptr, i64, ptr, ...)",
            "declare ptr @__xcc_aot_string_join(ptr, ptr)",
            "declare ptr @__xcc_aot_tuple_slice(ptr, i64, i64)",
            "",
            "define i64 @__xcc_aot_tuple_len(ptr %tuple) {",
            "entry:",
            "  %is_null = icmp eq ptr %tuple, null",
            "  br i1 %is_null, label %null, label %value",
            "null:",
            "  ret i64 0",
            "value:",
            "  %len = load i64, ptr %tuple",
            "  ret i64 %len",
            "}",
            "",
            "define ptr @__xcc_aot_tuple_get(ptr %tuple, i64 %index) {",
            "entry:",
            "  %is_null = icmp eq ptr %tuple, null",
            "  br i1 %is_null, label %null, label %value",
            "null:",
            "  ret ptr null",
            "value:",
            "  %slot_index = add i64 %index, 1",
            "  %slot = getelementptr ptr, ptr %tuple, i64 %slot_index",
            "  %item = load ptr, ptr %slot",
            "  ret ptr %item",
            "}",
            "",
            "define ptr @__xcc_aot_lexer_translate_source(ptr %source) {",
            "entry:",
            "  %len = call i64 @strlen(ptr %source)",
            "  %cap = add i64 %len, 1",
            "  %tmp = call ptr @malloc(i64 %cap)",
            "  %out = call ptr @malloc(i64 %cap)",
            "  %norm_i_ptr = alloca i64",
            "  %norm_j_ptr = alloca i64",
            "  store i64 0, ptr %norm_i_ptr",
            "  store i64 0, ptr %norm_j_ptr",
            "  br label %norm_cond",
            "norm_cond:",
            "  %norm_i = load i64, ptr %norm_i_ptr",
            "  %norm_done = icmp uge i64 %norm_i, %len",
            "  br i1 %norm_done, label %norm_end, label %norm_body",
            "norm_body:",
            "  %norm_i0 = load i64, ptr %norm_i_ptr",
            "  %norm_src_ptr = getelementptr i8, ptr %source, i64 %norm_i0",
            "  %norm_ch = load i8, ptr %norm_src_ptr",
            "  %norm_is_cr = icmp eq i8 %norm_ch, 13",
            "  br i1 %norm_is_cr, label %norm_cr, label %norm_not_cr",
            "norm_cr:",
            "  %norm_cr_i = load i64, ptr %norm_i_ptr",
            "  %norm_cr_next = add i64 %norm_cr_i, 1",
            "  %norm_cr_has_next = icmp ult i64 %norm_cr_next, %len",
            "  br i1 %norm_cr_has_next, label %norm_cr_load, label %norm_cr_single",
            "norm_cr_load:",
            "  %norm_cr_next_ptr = getelementptr i8, ptr %source, i64 %norm_cr_next",
            "  %norm_cr_next_ch = load i8, ptr %norm_cr_next_ptr",
            "  %norm_cr_is_lf = icmp eq i8 %norm_cr_next_ch, 10",
            "  br i1 %norm_cr_is_lf, label %norm_crlf, label %norm_cr_single",
            "norm_crlf:",
            "  %norm_crlf_i = load i64, ptr %norm_i_ptr",
            "  %norm_crlf_j = load i64, ptr %norm_j_ptr",
            "  %norm_crlf_dst = getelementptr i8, ptr %tmp, i64 %norm_crlf_j",
            "  store i8 10, ptr %norm_crlf_dst",
            "  %norm_crlf_next_i = add i64 %norm_crlf_i, 2",
            "  %norm_crlf_next_j = add i64 %norm_crlf_j, 1",
            "  store i64 %norm_crlf_next_i, ptr %norm_i_ptr",
            "  store i64 %norm_crlf_next_j, ptr %norm_j_ptr",
            "  br label %norm_cond",
            "norm_cr_single:",
            "  %norm_cr_single_i = load i64, ptr %norm_i_ptr",
            "  %norm_cr_single_j = load i64, ptr %norm_j_ptr",
            "  %norm_cr_single_dst = getelementptr i8, ptr %tmp, i64 %norm_cr_single_j",
            "  store i8 10, ptr %norm_cr_single_dst",
            "  %norm_cr_single_next_i = add i64 %norm_cr_single_i, 1",
            "  %norm_cr_single_next_j = add i64 %norm_cr_single_j, 1",
            "  store i64 %norm_cr_single_next_i, ptr %norm_i_ptr",
            "  store i64 %norm_cr_single_next_j, ptr %norm_j_ptr",
            "  br label %norm_cond",
            "norm_not_cr:",
            "  %tri_i = load i64, ptr %norm_i_ptr",
            "  %tri_is_q0 = icmp eq i8 %norm_ch, 63",
            "  %tri_i2 = add i64 %tri_i, 2",
            "  %tri_has_len = icmp ult i64 %tri_i2, %len",
            "  %tri_maybe = and i1 %tri_is_q0, %tri_has_len",
            "  br i1 %tri_maybe, label %tri_load, label %norm_copy",
            "tri_load:",
            "  %tri_i1 = add i64 %tri_i, 1",
            "  %tri_second_ptr = getelementptr i8, ptr %source, i64 %tri_i1",
            "  %tri_second = load i8, ptr %tri_second_ptr",
            "  %tri_third_ptr = getelementptr i8, ptr %source, i64 %tri_i2",
            "  %tri_third = load i8, ptr %tri_third_ptr",
            "  %tri_is_q1 = icmp eq i8 %tri_second, 63",
            "  br i1 %tri_is_q1, label %tri_replace, label %norm_copy",
            "tri_replace:",
            "  %tri_eq = icmp eq i8 %tri_third, 61",
            "  %tri_rep1 = select i1 %tri_eq, i8 35, i8 0",
            "  %tri_slash = icmp eq i8 %tri_third, 47",
            "  %tri_rep2 = select i1 %tri_slash, i8 92, i8 %tri_rep1",
            "  %tri_quote = icmp eq i8 %tri_third, 39",
            "  %tri_rep3 = select i1 %tri_quote, i8 94, i8 %tri_rep2",
            "  %tri_lparen = icmp eq i8 %tri_third, 40",
            "  %tri_rep4 = select i1 %tri_lparen, i8 91, i8 %tri_rep3",
            "  %tri_rparen = icmp eq i8 %tri_third, 41",
            "  %tri_rep5 = select i1 %tri_rparen, i8 93, i8 %tri_rep4",
            "  %tri_bang = icmp eq i8 %tri_third, 33",
            "  %tri_rep6 = select i1 %tri_bang, i8 124, i8 %tri_rep5",
            "  %tri_lt = icmp eq i8 %tri_third, 60",
            "  %tri_rep7 = select i1 %tri_lt, i8 123, i8 %tri_rep6",
            "  %tri_gt = icmp eq i8 %tri_third, 62",
            "  %tri_rep8 = select i1 %tri_gt, i8 125, i8 %tri_rep7",
            "  %tri_dash = icmp eq i8 %tri_third, 45",
            "  %tri_rep9 = select i1 %tri_dash, i8 126, i8 %tri_rep8",
            "  %tri_has_rep = icmp ne i8 %tri_rep9, 0",
            "  br i1 %tri_has_rep, label %tri_emit, label %norm_copy",
            "tri_emit:",
            "  %tri_emit_i = load i64, ptr %norm_i_ptr",
            "  %tri_emit_j = load i64, ptr %norm_j_ptr",
            "  %tri_emit_dst = getelementptr i8, ptr %tmp, i64 %tri_emit_j",
            "  store i8 %tri_rep9, ptr %tri_emit_dst",
            "  %tri_emit_next_i = add i64 %tri_emit_i, 3",
            "  %tri_emit_next_j = add i64 %tri_emit_j, 1",
            "  store i64 %tri_emit_next_i, ptr %norm_i_ptr",
            "  store i64 %tri_emit_next_j, ptr %norm_j_ptr",
            "  br label %norm_cond",
            "norm_copy:",
            "  %norm_copy_i = load i64, ptr %norm_i_ptr",
            "  %norm_copy_j = load i64, ptr %norm_j_ptr",
            "  %norm_copy_dst = getelementptr i8, ptr %tmp, i64 %norm_copy_j",
            "  store i8 %norm_ch, ptr %norm_copy_dst",
            "  %norm_copy_next_i = add i64 %norm_copy_i, 1",
            "  %norm_copy_next_j = add i64 %norm_copy_j, 1",
            "  store i64 %norm_copy_next_i, ptr %norm_i_ptr",
            "  store i64 %norm_copy_next_j, ptr %norm_j_ptr",
            "  br label %norm_cond",
            "norm_end:",
            "  %norm_len = load i64, ptr %norm_j_ptr",
            "  %tmp_zero_ptr = getelementptr i8, ptr %tmp, i64 %norm_len",
            "  store i8 0, ptr %tmp_zero_ptr",
            "  %splice_i_ptr = alloca i64",
            "  %splice_j_ptr = alloca i64",
            "  store i64 0, ptr %splice_i_ptr",
            "  store i64 0, ptr %splice_j_ptr",
            "  br label %splice_cond",
            "splice_cond:",
            "  %splice_i = load i64, ptr %splice_i_ptr",
            "  %splice_done = icmp uge i64 %splice_i, %norm_len",
            "  br i1 %splice_done, label %splice_end, label %splice_body",
            "splice_body:",
            "  %splice_i0 = load i64, ptr %splice_i_ptr",
            "  %splice_src_ptr = getelementptr i8, ptr %tmp, i64 %splice_i0",
            "  %splice_ch = load i8, ptr %splice_src_ptr",
            "  %splice_is_backslash = icmp eq i8 %splice_ch, 92",
            "  %splice_next_i = add i64 %splice_i0, 1",
            "  %splice_has_next = icmp ult i64 %splice_next_i, %norm_len",
            "  %splice_maybe = and i1 %splice_is_backslash, %splice_has_next",
            "  br i1 %splice_maybe, label %splice_load_next, label %splice_copy",
            "splice_load_next:",
            "  %splice_next_ptr = getelementptr i8, ptr %tmp, i64 %splice_next_i",
            "  %splice_next_ch = load i8, ptr %splice_next_ptr",
            "  %splice_is_lf = icmp eq i8 %splice_next_ch, 10",
            "  br i1 %splice_is_lf, label %splice_skip, label %splice_copy",
            "splice_skip:",
            "  %splice_skip_i = load i64, ptr %splice_i_ptr",
            "  %splice_skip_next_i = add i64 %splice_skip_i, 2",
            "  store i64 %splice_skip_next_i, ptr %splice_i_ptr",
            "  br label %splice_cond",
            "splice_copy:",
            "  %splice_copy_i = load i64, ptr %splice_i_ptr",
            "  %splice_copy_j = load i64, ptr %splice_j_ptr",
            "  %splice_dst = getelementptr i8, ptr %out, i64 %splice_copy_j",
            "  store i8 %splice_ch, ptr %splice_dst",
            "  %splice_copy_next_i = add i64 %splice_copy_i, 1",
            "  %splice_copy_next_j = add i64 %splice_copy_j, 1",
            "  store i64 %splice_copy_next_i, ptr %splice_i_ptr",
            "  store i64 %splice_copy_next_j, ptr %splice_j_ptr",
            "  br label %splice_cond",
            "splice_end:",
            "  %out_len = load i64, ptr %splice_j_ptr",
            "  %out_zero_ptr = getelementptr i8, ptr %out, i64 %out_len",
            "  store i8 0, ptr %out_zero_ptr",
            "  ret ptr %out",
            "}",
            "",
            "define ptr @__xcc_aot_i64_to_string(i64 %value) {",
            "entry:",
            "  %out = call ptr @malloc(i64 32)",
            "  %written = call i32 (ptr, i64, ptr, ...) @snprintf(",
            "    ptr %out,",
            "    i64 32,",
            "    ptr @__xcc_aot_fmt_i64,",
            "    i64 %value",
            "  )",
            "  ret ptr %out",
            "}",
            "",
            "define ptr @__xcc_aot_string_concat2(ptr %left, ptr %right) {",
            "entry:",
            "  %left_len = call i64 @strlen(ptr %left)",
            "  %right_len = call i64 @strlen(ptr %right)",
            "  %data_len = add i64 %left_len, %right_len",
            "  %total_len = add i64 %data_len, 1",
            "  %out = call ptr @malloc(i64 %total_len)",
            "  %copy_left = call ptr @memcpy(ptr %out, ptr %left, i64 %left_len)",
            "  %right_dst = getelementptr i8, ptr %out, i64 %left_len",
            "  %copy_right = call ptr @memcpy(ptr %right_dst, ptr %right, i64 %right_len)",
            "  %zero_ptr = getelementptr i8, ptr %out, i64 %data_len",
            "  store i8 0, ptr %zero_ptr",
            "  ret ptr %out",
            "}",
        )
    )
