def runtime_prelude() -> str:
    return "\n".join(
        (
            "declare i32 @puts(ptr)",
            "declare ptr @malloc(i64)",
            "declare i64 @strlen(ptr)",
            "declare ptr @memcpy(ptr, ptr, i64)",
            "declare i32 @strcmp(ptr, ptr)",
            "declare i32 @snprintf(ptr, i64, ptr, ...)",
            "declare ptr @__xcc_aot_string_join(ptr, ptr)",
            "declare ptr @__xcc_aot_tuple_pack(i64, ...)",
            "declare i64 @__xcc_aot_tuple_len(ptr)",
            "declare ptr @__xcc_aot_tuple_get(ptr, i64)",
            "declare ptr @__xcc_aot_tuple_slice(ptr, i64, i64)",
            "",
            "define ptr @__xcc_aot_string_concat2(ptr %left, ptr %right) {",
            "entry:",
            "  %left_len = call i64 @strlen(ptr %left)",
            "  %right_len = call i64 @strlen(ptr %right)",
            "  %data_len = add i64 %left_len, %right_len",
            "  %total_len = add i64 %data_len, 1",
            "  %out = call ptr @malloc(i64 %total_len)",
            "  %copy_left = call ptr @memcpy(ptr %out, ptr %left, i64 %left_len)",
            "  %right_dst = getelementptr i8, ptr %out, i64 %left_len",
            "  %copy_right = call ptr @memcpy(ptr %right_dst, ptr %right, i64 %right_len)",
            "  %zero_ptr = getelementptr i8, ptr %out, i64 %data_len",
            "  store i8 0, ptr %zero_ptr",
            "  ret ptr %out",
            "}",
        )
    )
