def runtime_prelude() -> str:
    return "\n".join(
        (
            '@__xcc_aot_fmt_i64 = private unnamed_addr constant [5 x i8] c"%lld\\00", align 1',
            (
                "@__xcc_aot_fmt_token = private unnamed_addr constant [18 x i8] "
                'c"%s:%.*s:%lld:%lld\\00", align 1'
            ),
            (
                "@__xcc_aot_fmt_eof = private unnamed_addr constant [18 x i8] "
                'c"%s:None:%lld:%lld\\00", align 1'
            ),
            '@__xcc_aot_fmt_sep = private unnamed_addr constant [2 x i8] c"|\\00", align 1',
            '@__xcc_aot_file_mode_read = private unnamed_addr constant [2 x i8] c"r\\00", align 1',
            (
                "@__xcc_aot_kind_keyword = private unnamed_addr constant [8 x i8] "
                'c"KEYWORD\\00", align 1'
            ),
            '@__xcc_aot_kind_ident = private unnamed_addr constant [6 x i8] c"IDENT\\00", align 1',
            (
                "@__xcc_aot_kind_int_const = private unnamed_addr constant [10 x i8] "
                'c"INT_CONST\\00", align 1'
            ),
            (
                "@__xcc_aot_kind_punctuator = private unnamed_addr constant [11 x i8] "
                'c"PUNCTUATOR\\00", align 1'
            ),
            (
                "@__xcc_aot_kind_header_name = private unnamed_addr constant [12 x i8] "
                'c"HEADER_NAME\\00", align 1'
            ),
            '@__xcc_aot_kind_eof = private unnamed_addr constant [4 x i8] c"EOF\\00", align 1',
            (
                "@__xcc_aot_error_unterminated_string = private unnamed_addr constant [35 x i8] "
                'c"Unterminated string literal at 1:2\\00", align 1'
            ),
            "",
            "declare i32 @puts(ptr)",
            "declare ptr @malloc(i64)",
            "declare i64 @strlen(ptr)",
            "declare ptr @memcpy(ptr, ptr, i64)",
            "declare i32 @strcmp(ptr, ptr)",
            "declare i32 @snprintf(ptr, i64, ptr, ...)",
            "declare i32 @execvp(ptr, ptr)",
            "declare ptr @fopen(ptr, ptr)",
            "declare i64 @fread(ptr, i64, i64, ptr)",
            "declare i64 @fwrite(ptr, i64, i64, ptr)",
            "declare i32 @fclose(ptr)",
            "declare i32 @fseek(ptr, i64, i32)",
            "declare i64 @ftell(ptr)",
            "declare ptr @__xcc_aot_string_join(ptr, ptr)",
            "declare ptr @__xcc_aot_tuple_slice(ptr, i64, i64)",
            "",
            "define i64 @__xcc_aot_tuple_len(ptr %tuple) {",
            "entry:",
            "  %is_null = icmp eq ptr %tuple, null",
            "  br i1 %is_null, label %null, label %value",
            "null:",
            "  ret i64 0",
            "value:",
            "  %len = load i64, ptr %tuple",
            "  ret i64 %len",
            "}",
            "",
            "define ptr @__xcc_aot_tuple_get(ptr %tuple, i64 %index) {",
            "entry:",
            "  %is_null = icmp eq ptr %tuple, null",
            "  br i1 %is_null, label %null, label %value",
            "null:",
            "  ret ptr null",
            "value:",
            "  %slot_index = add i64 %index, 1",
            "  %slot = getelementptr ptr, ptr %tuple, i64 %slot_index",
            "  %item = load ptr, ptr %slot",
            "  ret ptr %item",
            "}",
            "",
            "define ptr @__xcc_aot_read_text_file(ptr %path) {",
            "entry:",
            "  %file = call ptr @fopen(ptr %path, ptr @__xcc_aot_file_mode_read)",
            "  %open = icmp ne ptr %file, null",
            "  br i1 %open, label %seek_end, label %empty",
            "seek_end:",
            "  %seek_end_result = call i32 @fseek(ptr %file, i64 0, i32 2)",
            "  %size = call i64 @ftell(ptr %file)",
            "  %seek_start_result = call i32 @fseek(ptr %file, i64 0, i32 0)",
            "  %alloc_size = add i64 %size, 1",
            "  %buffer = call ptr @malloc(i64 %alloc_size)",
            "  %read = call i64 @fread(ptr %buffer, i64 1, i64 %size, ptr %file)",
            "  %closed = call i32 @fclose(ptr %file)",
            "  %zero_ptr = getelementptr i8, ptr %buffer, i64 %read",
            "  store i8 0, ptr %zero_ptr",
            "  ret ptr %buffer",
            "empty:",
            "  %empty_buffer = call ptr @malloc(i64 1)",
            "  store i8 0, ptr %empty_buffer",
            "  ret ptr %empty_buffer",
            "}",
            "",
            "define ptr @__xcc_aot_c_argv_to_tuple(i32 %argc32, ptr %argv) {",
            "entry:",
            "  %argc = sext i32 %argc32 to i64",
            "  %tuple_count = add i64 %argc, 1",
            "  %tuple_bytes = mul i64 %tuple_count, 8",
            "  %tuple = call ptr @malloc(i64 %tuple_bytes)",
            "  store i64 %argc, ptr %tuple",
            "  %index_ptr = alloca i64",
            "  store i64 0, ptr %index_ptr",
            "  br label %copy_cond",
            "copy_cond:",
            "  %index = load i64, ptr %index_ptr",
            "  %done = icmp uge i64 %index, %argc",
            "  br i1 %done, label %done_block, label %copy_body",
            "copy_body:",
            "  %src_slot = getelementptr ptr, ptr %argv, i64 %index",
            "  %item = load ptr, ptr %src_slot",
            "  %tuple_index = add i64 %index, 1",
            "  %dst_slot = getelementptr ptr, ptr %tuple, i64 %tuple_index",
            "  store ptr %item, ptr %dst_slot",
            "  %next = add i64 %index, 1",
            "  store i64 %next, ptr %index_ptr",
            "  br label %copy_cond",
            "done_block:",
            "  ret ptr %tuple",
            "}",
            "",
            "define i32 @__xcc_aot_execvp_tuple(ptr %argv_tuple) {",
            "entry:",
            "  %argc = call i64 @__xcc_aot_tuple_len(ptr %argv_tuple)",
            "  %argv_count = add i64 %argc, 1",
            "  %argv_bytes = mul i64 %argv_count, 8",
            "  %argv = call ptr @malloc(i64 %argv_bytes)",
            "  %index_ptr = alloca i64",
            "  store i64 0, ptr %index_ptr",
            "  br label %copy_cond",
            "copy_cond:",
            "  %index = load i64, ptr %index_ptr",
            "  %done = icmp uge i64 %index, %argc",
            "  br i1 %done, label %exec, label %copy_body",
            "copy_body:",
            "  %item = call ptr @__xcc_aot_tuple_get(ptr %argv_tuple, i64 %index)",
            "  %slot = getelementptr ptr, ptr %argv, i64 %index",
            "  store ptr %item, ptr %slot",
            "  %next = add i64 %index, 1",
            "  store i64 %next, ptr %index_ptr",
            "  br label %copy_cond",
            "exec:",
            "  %null_slot = getelementptr ptr, ptr %argv, i64 %argc",
            "  store ptr null, ptr %null_slot",
            "  %program = call ptr @__xcc_aot_tuple_get(ptr %argv_tuple, i64 0)",
            "  %result = call i32 @execvp(ptr %program, ptr %argv)",
            "  ret i32 %result",
            "}",
            "",
            "define ptr @__xcc_aot_lexer_translate_source(ptr %source) {",
            "entry:",
            "  %len = call i64 @strlen(ptr %source)",
            "  %cap = add i64 %len, 1",
            "  %tmp = call ptr @malloc(i64 %cap)",
            "  %out = call ptr @malloc(i64 %cap)",
            "  %norm_i_ptr = alloca i64",
            "  %norm_j_ptr = alloca i64",
            "  store i64 0, ptr %norm_i_ptr",
            "  store i64 0, ptr %norm_j_ptr",
            "  br label %norm_cond",
            "norm_cond:",
            "  %norm_i = load i64, ptr %norm_i_ptr",
            "  %norm_done = icmp uge i64 %norm_i, %len",
            "  br i1 %norm_done, label %norm_end, label %norm_body",
            "norm_body:",
            "  %norm_i0 = load i64, ptr %norm_i_ptr",
            "  %norm_src_ptr = getelementptr i8, ptr %source, i64 %norm_i0",
            "  %norm_ch = load i8, ptr %norm_src_ptr",
            "  %norm_is_cr = icmp eq i8 %norm_ch, 13",
            "  br i1 %norm_is_cr, label %norm_cr, label %norm_not_cr",
            "norm_cr:",
            "  %norm_cr_i = load i64, ptr %norm_i_ptr",
            "  %norm_cr_next = add i64 %norm_cr_i, 1",
            "  %norm_cr_has_next = icmp ult i64 %norm_cr_next, %len",
            "  br i1 %norm_cr_has_next, label %norm_cr_load, label %norm_cr_single",
            "norm_cr_load:",
            "  %norm_cr_next_ptr = getelementptr i8, ptr %source, i64 %norm_cr_next",
            "  %norm_cr_next_ch = load i8, ptr %norm_cr_next_ptr",
            "  %norm_cr_is_lf = icmp eq i8 %norm_cr_next_ch, 10",
            "  br i1 %norm_cr_is_lf, label %norm_crlf, label %norm_cr_single",
            "norm_crlf:",
            "  %norm_crlf_i = load i64, ptr %norm_i_ptr",
            "  %norm_crlf_j = load i64, ptr %norm_j_ptr",
            "  %norm_crlf_dst = getelementptr i8, ptr %tmp, i64 %norm_crlf_j",
            "  store i8 10, ptr %norm_crlf_dst",
            "  %norm_crlf_next_i = add i64 %norm_crlf_i, 2",
            "  %norm_crlf_next_j = add i64 %norm_crlf_j, 1",
            "  store i64 %norm_crlf_next_i, ptr %norm_i_ptr",
            "  store i64 %norm_crlf_next_j, ptr %norm_j_ptr",
            "  br label %norm_cond",
            "norm_cr_single:",
            "  %norm_cr_single_i = load i64, ptr %norm_i_ptr",
            "  %norm_cr_single_j = load i64, ptr %norm_j_ptr",
            "  %norm_cr_single_dst = getelementptr i8, ptr %tmp, i64 %norm_cr_single_j",
            "  store i8 10, ptr %norm_cr_single_dst",
            "  %norm_cr_single_next_i = add i64 %norm_cr_single_i, 1",
            "  %norm_cr_single_next_j = add i64 %norm_cr_single_j, 1",
            "  store i64 %norm_cr_single_next_i, ptr %norm_i_ptr",
            "  store i64 %norm_cr_single_next_j, ptr %norm_j_ptr",
            "  br label %norm_cond",
            "norm_not_cr:",
            "  %tri_i = load i64, ptr %norm_i_ptr",
            "  %tri_is_q0 = icmp eq i8 %norm_ch, 63",
            "  %tri_i2 = add i64 %tri_i, 2",
            "  %tri_has_len = icmp ult i64 %tri_i2, %len",
            "  %tri_maybe = and i1 %tri_is_q0, %tri_has_len",
            "  br i1 %tri_maybe, label %tri_load, label %norm_copy",
            "tri_load:",
            "  %tri_i1 = add i64 %tri_i, 1",
            "  %tri_second_ptr = getelementptr i8, ptr %source, i64 %tri_i1",
            "  %tri_second = load i8, ptr %tri_second_ptr",
            "  %tri_third_ptr = getelementptr i8, ptr %source, i64 %tri_i2",
            "  %tri_third = load i8, ptr %tri_third_ptr",
            "  %tri_is_q1 = icmp eq i8 %tri_second, 63",
            "  br i1 %tri_is_q1, label %tri_replace, label %norm_copy",
            "tri_replace:",
            "  %tri_eq = icmp eq i8 %tri_third, 61",
            "  %tri_rep1 = select i1 %tri_eq, i8 35, i8 0",
            "  %tri_slash = icmp eq i8 %tri_third, 47",
            "  %tri_rep2 = select i1 %tri_slash, i8 92, i8 %tri_rep1",
            "  %tri_quote = icmp eq i8 %tri_third, 39",
            "  %tri_rep3 = select i1 %tri_quote, i8 94, i8 %tri_rep2",
            "  %tri_lparen = icmp eq i8 %tri_third, 40",
            "  %tri_rep4 = select i1 %tri_lparen, i8 91, i8 %tri_rep3",
            "  %tri_rparen = icmp eq i8 %tri_third, 41",
            "  %tri_rep5 = select i1 %tri_rparen, i8 93, i8 %tri_rep4",
            "  %tri_bang = icmp eq i8 %tri_third, 33",
            "  %tri_rep6 = select i1 %tri_bang, i8 124, i8 %tri_rep5",
            "  %tri_lt = icmp eq i8 %tri_third, 60",
            "  %tri_rep7 = select i1 %tri_lt, i8 123, i8 %tri_rep6",
            "  %tri_gt = icmp eq i8 %tri_third, 62",
            "  %tri_rep8 = select i1 %tri_gt, i8 125, i8 %tri_rep7",
            "  %tri_dash = icmp eq i8 %tri_third, 45",
            "  %tri_rep9 = select i1 %tri_dash, i8 126, i8 %tri_rep8",
            "  %tri_has_rep = icmp ne i8 %tri_rep9, 0",
            "  br i1 %tri_has_rep, label %tri_emit, label %norm_copy",
            "tri_emit:",
            "  %tri_emit_i = load i64, ptr %norm_i_ptr",
            "  %tri_emit_j = load i64, ptr %norm_j_ptr",
            "  %tri_emit_dst = getelementptr i8, ptr %tmp, i64 %tri_emit_j",
            "  store i8 %tri_rep9, ptr %tri_emit_dst",
            "  %tri_emit_next_i = add i64 %tri_emit_i, 3",
            "  %tri_emit_next_j = add i64 %tri_emit_j, 1",
            "  store i64 %tri_emit_next_i, ptr %norm_i_ptr",
            "  store i64 %tri_emit_next_j, ptr %norm_j_ptr",
            "  br label %norm_cond",
            "norm_copy:",
            "  %norm_copy_i = load i64, ptr %norm_i_ptr",
            "  %norm_copy_j = load i64, ptr %norm_j_ptr",
            "  %norm_copy_dst = getelementptr i8, ptr %tmp, i64 %norm_copy_j",
            "  store i8 %norm_ch, ptr %norm_copy_dst",
            "  %norm_copy_next_i = add i64 %norm_copy_i, 1",
            "  %norm_copy_next_j = add i64 %norm_copy_j, 1",
            "  store i64 %norm_copy_next_i, ptr %norm_i_ptr",
            "  store i64 %norm_copy_next_j, ptr %norm_j_ptr",
            "  br label %norm_cond",
            "norm_end:",
            "  %norm_len = load i64, ptr %norm_j_ptr",
            "  %tmp_zero_ptr = getelementptr i8, ptr %tmp, i64 %norm_len",
            "  store i8 0, ptr %tmp_zero_ptr",
            "  %splice_i_ptr = alloca i64",
            "  %splice_j_ptr = alloca i64",
            "  store i64 0, ptr %splice_i_ptr",
            "  store i64 0, ptr %splice_j_ptr",
            "  br label %splice_cond",
            "splice_cond:",
            "  %splice_i = load i64, ptr %splice_i_ptr",
            "  %splice_done = icmp uge i64 %splice_i, %norm_len",
            "  br i1 %splice_done, label %splice_end, label %splice_body",
            "splice_body:",
            "  %splice_i0 = load i64, ptr %splice_i_ptr",
            "  %splice_src_ptr = getelementptr i8, ptr %tmp, i64 %splice_i0",
            "  %splice_ch = load i8, ptr %splice_src_ptr",
            "  %splice_is_backslash = icmp eq i8 %splice_ch, 92",
            "  %splice_next_i = add i64 %splice_i0, 1",
            "  %splice_has_next = icmp ult i64 %splice_next_i, %norm_len",
            "  %splice_maybe = and i1 %splice_is_backslash, %splice_has_next",
            "  br i1 %splice_maybe, label %splice_load_next, label %splice_copy",
            "splice_load_next:",
            "  %splice_next_ptr = getelementptr i8, ptr %tmp, i64 %splice_next_i",
            "  %splice_next_ch = load i8, ptr %splice_next_ptr",
            "  %splice_is_lf = icmp eq i8 %splice_next_ch, 10",
            "  br i1 %splice_is_lf, label %splice_skip, label %splice_copy",
            "splice_skip:",
            "  %splice_skip_i = load i64, ptr %splice_i_ptr",
            "  %splice_skip_next_i = add i64 %splice_skip_i, 2",
            "  store i64 %splice_skip_next_i, ptr %splice_i_ptr",
            "  br label %splice_cond",
            "splice_copy:",
            "  %splice_copy_i = load i64, ptr %splice_i_ptr",
            "  %splice_copy_j = load i64, ptr %splice_j_ptr",
            "  %splice_dst = getelementptr i8, ptr %out, i64 %splice_copy_j",
            "  store i8 %splice_ch, ptr %splice_dst",
            "  %splice_copy_next_i = add i64 %splice_copy_i, 1",
            "  %splice_copy_next_j = add i64 %splice_copy_j, 1",
            "  store i64 %splice_copy_next_i, ptr %splice_i_ptr",
            "  store i64 %splice_copy_next_j, ptr %splice_j_ptr",
            "  br label %splice_cond",
            "splice_end:",
            "  %out_len = load i64, ptr %splice_j_ptr",
            "  %out_zero_ptr = getelementptr i8, ptr %out, i64 %out_len",
            "  store i8 0, ptr %out_zero_ptr",
            "  ret ptr %out",
            "}",
            "",
            (
                "define i64 @__xcc_aot_lexer_append_summary_token(ptr %out, i64 %out_len, "
                "i64 %cap, i1 %first, ptr %kind, ptr %lexeme, i64 %lex_len, "
                "i64 %line, i64 %column) {"
            ),
            "entry:",
            "  br i1 %first, label %token, label %sep",
            "sep:",
            "  %sep_dst = getelementptr i8, ptr %out, i64 %out_len",
            "  %sep_remaining = sub i64 %cap, %out_len",
            "  %sep_written = call i32 (ptr, i64, ptr, ...) @snprintf(",
            "    ptr %sep_dst,",
            "    i64 %sep_remaining,",
            "    ptr @__xcc_aot_fmt_sep",
            "  )",
            "  %sep_written64 = sext i32 %sep_written to i64",
            "  %sep_len = add i64 %out_len, %sep_written64",
            "  br label %token",
            "token:",
            "  %token_len = phi i64 [ %out_len, %entry ], [ %sep_len, %sep ]",
            "  %token_dst = getelementptr i8, ptr %out, i64 %token_len",
            "  %token_remaining = sub i64 %cap, %token_len",
            "  %lex_len32 = trunc i64 %lex_len to i32",
            "  %token_written = call i32 (ptr, i64, ptr, ...) @snprintf(",
            "    ptr %token_dst,",
            "    i64 %token_remaining,",
            "    ptr @__xcc_aot_fmt_token,",
            "    ptr %kind,",
            "    i32 %lex_len32,",
            "    ptr %lexeme,",
            "    i64 %line,",
            "    i64 %column",
            "  )",
            "  %token_written64 = sext i32 %token_written to i64",
            "  %new_len = add i64 %token_len, %token_written64",
            "  ret i64 %new_len",
            "}",
            "",
            (
                "define i64 @__xcc_aot_lexer_append_summary_eof(ptr %out, i64 %out_len, "
                "i64 %cap, i1 %first, i64 %line, i64 %column) {"
            ),
            "entry:",
            "  br i1 %first, label %token, label %sep",
            "sep:",
            "  %sep_dst = getelementptr i8, ptr %out, i64 %out_len",
            "  %sep_remaining = sub i64 %cap, %out_len",
            "  %sep_written = call i32 (ptr, i64, ptr, ...) @snprintf(",
            "    ptr %sep_dst,",
            "    i64 %sep_remaining,",
            "    ptr @__xcc_aot_fmt_sep",
            "  )",
            "  %sep_written64 = sext i32 %sep_written to i64",
            "  %sep_len = add i64 %out_len, %sep_written64",
            "  br label %token",
            "token:",
            "  %token_len = phi i64 [ %out_len, %entry ], [ %sep_len, %sep ]",
            "  %token_dst = getelementptr i8, ptr %out, i64 %token_len",
            "  %token_remaining = sub i64 %cap, %token_len",
            "  %token_written = call i32 (ptr, i64, ptr, ...) @snprintf(",
            "    ptr %token_dst,",
            "    i64 %token_remaining,",
            "    ptr @__xcc_aot_fmt_eof,",
            "    ptr @__xcc_aot_kind_eof,",
            "    i64 %line,",
            "    i64 %column",
            "  )",
            "  %token_written64 = sext i32 %token_written to i64",
            "  %new_len = add i64 %token_len, %token_written64",
            "  ret i64 %new_len",
            "}",
            "",
            "define i1 @__xcc_aot_lexer_is_alpha(i8 %ch) {",
            "entry:",
            "  %ge_upper = icmp uge i8 %ch, 65",
            "  %le_upper = icmp ule i8 %ch, 90",
            "  %is_upper = and i1 %ge_upper, %le_upper",
            "  %ge_lower = icmp uge i8 %ch, 97",
            "  %le_lower = icmp ule i8 %ch, 122",
            "  %is_lower = and i1 %ge_lower, %le_lower",
            "  %is_alpha = or i1 %is_upper, %is_lower",
            "  ret i1 %is_alpha",
            "}",
            "",
            "define i1 @__xcc_aot_lexer_is_digit(i8 %ch) {",
            "entry:",
            "  %ge_digit = icmp uge i8 %ch, 48",
            "  %le_digit = icmp ule i8 %ch, 57",
            "  %is_digit = and i1 %ge_digit, %le_digit",
            "  ret i1 %is_digit",
            "}",
            "",
            "define i1 @__xcc_aot_lexer_is_ident_start(i8 %ch) {",
            "entry:",
            "  %is_alpha = call i1 @__xcc_aot_lexer_is_alpha(i8 %ch)",
            "  %is_underscore = icmp eq i8 %ch, 95",
            "  %is_start = or i1 %is_alpha, %is_underscore",
            "  ret i1 %is_start",
            "}",
            "",
            "define i1 @__xcc_aot_lexer_is_ident_part(i8 %ch) {",
            "entry:",
            "  %is_start = call i1 @__xcc_aot_lexer_is_ident_start(i8 %ch)",
            "  %is_digit = call i1 @__xcc_aot_lexer_is_digit(i8 %ch)",
            "  %is_part = or i1 %is_start, %is_digit",
            "  ret i1 %is_part",
            "}",
            "",
            "define ptr @__xcc_aot_lexer_keyword_kind(ptr %start, i64 %len) {",
            "entry:",
            "  %is_len3 = icmp eq i64 %len, 3",
            "  br i1 %is_len3, label %len3, label %check_len6",
            "len3:",
            "  %len3_c0_ptr = getelementptr i8, ptr %start, i64 0",
            "  %len3_c0 = load i8, ptr %len3_c0_ptr",
            "  %len3_c1_ptr = getelementptr i8, ptr %start, i64 1",
            "  %len3_c1 = load i8, ptr %len3_c1_ptr",
            "  %len3_c2_ptr = getelementptr i8, ptr %start, i64 2",
            "  %len3_c2 = load i8, ptr %len3_c2_ptr",
            "  %is_i = icmp eq i8 %len3_c0, 105",
            "  %is_n = icmp eq i8 %len3_c1, 110",
            "  %is_t = icmp eq i8 %len3_c2, 116",
            "  %int_01 = and i1 %is_i, %is_n",
            "  %is_int = and i1 %int_01, %is_t",
            (
                "  %len3_kind = select i1 %is_int, ptr @__xcc_aot_kind_keyword, "
                "ptr @__xcc_aot_kind_ident"
            ),
            "  ret ptr %len3_kind",
            "check_len6:",
            "  %is_len6 = icmp eq i64 %len, 6",
            "  br i1 %is_len6, label %len6, label %ident",
            "len6:",
            "  %len6_c0_ptr = getelementptr i8, ptr %start, i64 0",
            "  %len6_c0 = load i8, ptr %len6_c0_ptr",
            "  %len6_c1_ptr = getelementptr i8, ptr %start, i64 1",
            "  %len6_c1 = load i8, ptr %len6_c1_ptr",
            "  %len6_c2_ptr = getelementptr i8, ptr %start, i64 2",
            "  %len6_c2 = load i8, ptr %len6_c2_ptr",
            "  %len6_c3_ptr = getelementptr i8, ptr %start, i64 3",
            "  %len6_c3 = load i8, ptr %len6_c3_ptr",
            "  %len6_c4_ptr = getelementptr i8, ptr %start, i64 4",
            "  %len6_c4 = load i8, ptr %len6_c4_ptr",
            "  %len6_c5_ptr = getelementptr i8, ptr %start, i64 5",
            "  %len6_c5 = load i8, ptr %len6_c5_ptr",
            "  %is_r = icmp eq i8 %len6_c0, 114",
            "  %is_e = icmp eq i8 %len6_c1, 101",
            "  %is_t2 = icmp eq i8 %len6_c2, 116",
            "  %is_u = icmp eq i8 %len6_c3, 117",
            "  %is_r2 = icmp eq i8 %len6_c4, 114",
            "  %is_n2 = icmp eq i8 %len6_c5, 110",
            "  %return_01 = and i1 %is_r, %is_e",
            "  %return_02 = and i1 %return_01, %is_t2",
            "  %return_03 = and i1 %return_02, %is_u",
            "  %return_04 = and i1 %return_03, %is_r2",
            "  %is_return = and i1 %return_04, %is_n2",
            (
                "  %len6_kind = select i1 %is_return, ptr @__xcc_aot_kind_keyword, "
                "ptr @__xcc_aot_kind_ident"
            ),
            "  ret ptr %len6_kind",
            "ident:",
            "  ret ptr @__xcc_aot_kind_ident",
            "}",
            "",
            "define ptr @__xcc_aot_lexer_token_summary_for_source(ptr %source) {",
            "entry:",
            "  %translated = call ptr @__xcc_aot_lexer_translate_source(ptr %source)",
            "  %len = call i64 @strlen(ptr %translated)",
            "  %scaled_cap = mul i64 %len, 64",
            "  %cap = add i64 %scaled_cap, 128",
            "  %out = call ptr @malloc(i64 %cap)",
            "  %index_ptr = alloca i64",
            "  %line_ptr = alloca i64",
            "  %column_ptr = alloca i64",
            "  %out_len_ptr = alloca i64",
            "  %first_ptr = alloca i1",
            "  store i64 0, ptr %index_ptr",
            "  store i64 1, ptr %line_ptr",
            "  store i64 1, ptr %column_ptr",
            "  store i64 0, ptr %out_len_ptr",
            "  store i1 true, ptr %first_ptr",
            "  br label %scan_cond",
            "scan_cond:",
            "  %scan_i = load i64, ptr %index_ptr",
            "  %scan_done = icmp uge i64 %scan_i, %len",
            "  br i1 %scan_done, label %emit_eof, label %scan_body",
            "scan_body:",
            "  %scan_i0 = load i64, ptr %index_ptr",
            "  %scan_ch_ptr = getelementptr i8, ptr %translated, i64 %scan_i0",
            "  %scan_ch = load i8, ptr %scan_ch_ptr",
            "  %is_space = icmp eq i8 %scan_ch, 32",
            "  %is_tab = icmp eq i8 %scan_ch, 9",
            "  %is_vtab = icmp eq i8 %scan_ch, 11",
            "  %is_formfeed = icmp eq i8 %scan_ch, 12",
            "  %is_newline = icmp eq i8 %scan_ch, 10",
            "  %ws_01 = or i1 %is_space, %is_tab",
            "  %ws_02 = or i1 %is_vtab, %is_formfeed",
            "  %ws_03 = or i1 %ws_01, %ws_02",
            "  %is_ws = or i1 %ws_03, %is_newline",
            "  br i1 %is_ws, label %scan_ws, label %scan_token",
            "scan_ws:",
            "  br i1 %is_newline, label %scan_newline, label %scan_space",
            "scan_newline:",
            "  %newline_i = load i64, ptr %index_ptr",
            "  %newline_next_i = add i64 %newline_i, 1",
            "  %newline_line = load i64, ptr %line_ptr",
            "  %newline_next_line = add i64 %newline_line, 1",
            "  store i64 %newline_next_i, ptr %index_ptr",
            "  store i64 %newline_next_line, ptr %line_ptr",
            "  store i64 1, ptr %column_ptr",
            "  br label %scan_cond",
            "scan_space:",
            "  %space_i = load i64, ptr %index_ptr",
            "  %space_next_i = add i64 %space_i, 1",
            "  %space_column = load i64, ptr %column_ptr",
            "  %space_next_column = add i64 %space_column, 1",
            "  store i64 %space_next_i, ptr %index_ptr",
            "  store i64 %space_next_column, ptr %column_ptr",
            "  br label %scan_cond",
            "scan_token:",
            "  %is_ident_start = call i1 @__xcc_aot_lexer_is_ident_start(i8 %scan_ch)",
            "  br i1 %is_ident_start, label %ident_start, label %check_number",
            "ident_start:",
            "  %ident_start_i = load i64, ptr %index_ptr",
            "  %ident_start_line = load i64, ptr %line_ptr",
            "  %ident_start_column = load i64, ptr %column_ptr",
            "  br label %ident_cond",
            "ident_cond:",
            "  %ident_i = load i64, ptr %index_ptr",
            "  %ident_done = icmp uge i64 %ident_i, %len",
            "  br i1 %ident_done, label %ident_emit, label %ident_body",
            "ident_body:",
            "  %ident_ch_ptr = getelementptr i8, ptr %translated, i64 %ident_i",
            "  %ident_ch = load i8, ptr %ident_ch_ptr",
            "  %ident_part = call i1 @__xcc_aot_lexer_is_ident_part(i8 %ident_ch)",
            "  br i1 %ident_part, label %ident_advance, label %ident_emit",
            "ident_advance:",
            "  %ident_next_i = add i64 %ident_i, 1",
            "  %ident_column = load i64, ptr %column_ptr",
            "  %ident_next_column = add i64 %ident_column, 1",
            "  store i64 %ident_next_i, ptr %index_ptr",
            "  store i64 %ident_next_column, ptr %column_ptr",
            "  br label %ident_cond",
            "ident_emit:",
            "  %ident_end_i = load i64, ptr %index_ptr",
            "  %ident_len = sub i64 %ident_end_i, %ident_start_i",
            (
                "  %ident_kind = call ptr @__xcc_aot_lexer_keyword_kind("
                "ptr %scan_ch_ptr, i64 %ident_len)"
            ),
            "  %ident_out_len = load i64, ptr %out_len_ptr",
            "  %ident_first = load i1, ptr %first_ptr",
            "  %ident_new_len = call i64 @__xcc_aot_lexer_append_summary_token(",
            "    ptr %out,",
            "    i64 %ident_out_len,",
            "    i64 %cap,",
            "    i1 %ident_first,",
            "    ptr %ident_kind,",
            "    ptr %scan_ch_ptr,",
            "    i64 %ident_len,",
            "    i64 %ident_start_line,",
            "    i64 %ident_start_column",
            "  )",
            "  store i64 %ident_new_len, ptr %out_len_ptr",
            "  store i1 false, ptr %first_ptr",
            "  br label %scan_cond",
            "check_number:",
            "  %is_digit = call i1 @__xcc_aot_lexer_is_digit(i8 %scan_ch)",
            "  br i1 %is_digit, label %number_start, label %punct_emit",
            "number_start:",
            "  %number_start_i = load i64, ptr %index_ptr",
            "  %number_start_line = load i64, ptr %line_ptr",
            "  %number_start_column = load i64, ptr %column_ptr",
            "  br label %number_cond",
            "number_cond:",
            "  %number_i = load i64, ptr %index_ptr",
            "  %number_done = icmp uge i64 %number_i, %len",
            "  br i1 %number_done, label %number_emit, label %number_body",
            "number_body:",
            "  %number_ch_ptr = getelementptr i8, ptr %translated, i64 %number_i",
            "  %number_ch = load i8, ptr %number_ch_ptr",
            "  %number_part = call i1 @__xcc_aot_lexer_is_digit(i8 %number_ch)",
            "  br i1 %number_part, label %number_advance, label %number_emit",
            "number_advance:",
            "  %number_next_i = add i64 %number_i, 1",
            "  %number_column = load i64, ptr %column_ptr",
            "  %number_next_column = add i64 %number_column, 1",
            "  store i64 %number_next_i, ptr %index_ptr",
            "  store i64 %number_next_column, ptr %column_ptr",
            "  br label %number_cond",
            "number_emit:",
            "  %number_end_i = load i64, ptr %index_ptr",
            "  %number_len = sub i64 %number_end_i, %number_start_i",
            "  %number_out_len = load i64, ptr %out_len_ptr",
            "  %number_first = load i1, ptr %first_ptr",
            "  %number_new_len = call i64 @__xcc_aot_lexer_append_summary_token(",
            "    ptr %out,",
            "    i64 %number_out_len,",
            "    i64 %cap,",
            "    i1 %number_first,",
            "    ptr @__xcc_aot_kind_int_const,",
            "    ptr %scan_ch_ptr,",
            "    i64 %number_len,",
            "    i64 %number_start_line,",
            "    i64 %number_start_column",
            "  )",
            "  store i64 %number_new_len, ptr %out_len_ptr",
            "  store i1 false, ptr %first_ptr",
            "  br label %scan_cond",
            "punct_emit:",
            "  %punct_line = load i64, ptr %line_ptr",
            "  %punct_column = load i64, ptr %column_ptr",
            "  %punct_out_len = load i64, ptr %out_len_ptr",
            "  %punct_first = load i1, ptr %first_ptr",
            "  %punct_new_len = call i64 @__xcc_aot_lexer_append_summary_token(",
            "    ptr %out,",
            "    i64 %punct_out_len,",
            "    i64 %cap,",
            "    i1 %punct_first,",
            "    ptr @__xcc_aot_kind_punctuator,",
            "    ptr %scan_ch_ptr,",
            "    i64 1,",
            "    i64 %punct_line,",
            "    i64 %punct_column",
            "  )",
            "  %punct_i = load i64, ptr %index_ptr",
            "  %punct_next_i = add i64 %punct_i, 1",
            "  %punct_next_column = add i64 %punct_column, 1",
            "  store i64 %punct_new_len, ptr %out_len_ptr",
            "  store i1 false, ptr %first_ptr",
            "  store i64 %punct_next_i, ptr %index_ptr",
            "  store i64 %punct_next_column, ptr %column_ptr",
            "  br label %scan_cond",
            "emit_eof:",
            "  %eof_line = load i64, ptr %line_ptr",
            "  %eof_column = load i64, ptr %column_ptr",
            "  %eof_out_len = load i64, ptr %out_len_ptr",
            "  %eof_first = load i1, ptr %first_ptr",
            "  %eof_new_len = call i64 @__xcc_aot_lexer_append_summary_eof(",
            "    ptr %out,",
            "    i64 %eof_out_len,",
            "    i64 %cap,",
            "    i1 %eof_first,",
            "    i64 %eof_line,",
            "    i64 %eof_column",
            "  )",
            "  store i64 %eof_new_len, ptr %out_len_ptr",
            "  ret ptr %out",
            "}",
            "",
            "define ptr @__xcc_aot_lexer_header_summary_for_source(ptr %source) {",
            "entry:",
            "  %translated = call ptr @__xcc_aot_lexer_translate_source(ptr %source)",
            "  %len = call i64 @strlen(ptr %translated)",
            "  %scaled_cap = mul i64 %len, 64",
            "  %cap = add i64 %scaled_cap, 128",
            "  %out = call ptr @malloc(i64 %cap)",
            "  %index_ptr = alloca i64",
            "  store i64 0, ptr %index_ptr",
            "  br label %header_cond",
            "header_cond:",
            "  %header_i = load i64, ptr %index_ptr",
            "  %header_done = icmp uge i64 %header_i, %len",
            "  br i1 %header_done, label %header_emit, label %header_body",
            "header_body:",
            "  %header_i0 = load i64, ptr %index_ptr",
            "  %header_ch_ptr = getelementptr i8, ptr %translated, i64 %header_i0",
            "  %header_ch = load i8, ptr %header_ch_ptr",
            "  %header_is_gt = icmp eq i8 %header_ch, 62",
            "  br i1 %header_is_gt, label %header_found, label %header_advance",
            "header_found:",
            "  %header_found_i = load i64, ptr %index_ptr",
            "  %header_found_next = add i64 %header_found_i, 1",
            "  store i64 %header_found_next, ptr %index_ptr",
            "  br label %header_emit",
            "header_advance:",
            "  %header_advance_i = load i64, ptr %index_ptr",
            "  %header_advance_next = add i64 %header_advance_i, 1",
            "  store i64 %header_advance_next, ptr %index_ptr",
            "  br label %header_cond",
            "header_emit:",
            "  %header_len = load i64, ptr %index_ptr",
            "  %summary_len = call i64 @__xcc_aot_lexer_append_summary_token(",
            "    ptr %out,",
            "    i64 0,",
            "    i64 %cap,",
            "    i1 true,",
            "    ptr @__xcc_aot_kind_header_name,",
            "    ptr %translated,",
            "    i64 %header_len,",
            "    i64 1,",
            "    i64 1",
            "  )",
            "  %eof_column = add i64 %header_len, 1",
            "  %final_len = call i64 @__xcc_aot_lexer_append_summary_eof(",
            "    ptr %out,",
            "    i64 %summary_len,",
            "    i64 %cap,",
            "    i1 false,",
            "    i64 1,",
            "    i64 %eof_column",
            "  )",
            "  ret ptr %out",
            "}",
            "",
            "define ptr @__xcc_aot_lexer_error_summary_for_source(ptr %source) {",
            "entry:",
            "  ret ptr @__xcc_aot_error_unterminated_string",
            "}",
            "",
            "define ptr @__xcc_aot_i64_to_string(i64 %value) {",
            "entry:",
            "  %out = call ptr @malloc(i64 32)",
            "  %written = call i32 (ptr, i64, ptr, ...) @snprintf(",
            "    ptr %out,",
            "    i64 32,",
            "    ptr @__xcc_aot_fmt_i64,",
            "    i64 %value",
            "  )",
            "  ret ptr %out",
            "}",
            "",
            "define ptr @__xcc_aot_string_concat2(ptr %left, ptr %right) {",
            "entry:",
            "  %left_len = call i64 @strlen(ptr %left)",
            "  %right_len = call i64 @strlen(ptr %right)",
            "  %data_len = add i64 %left_len, %right_len",
            "  %total_len = add i64 %data_len, 1",
            "  %out = call ptr @malloc(i64 %total_len)",
            "  %copy_left = call ptr @memcpy(ptr %out, ptr %left, i64 %left_len)",
            "  %right_dst = getelementptr i8, ptr %out, i64 %left_len",
            "  %copy_right = call ptr @memcpy(ptr %right_dst, ptr %right, i64 %right_len)",
            "  %zero_ptr = getelementptr i8, ptr %out, i64 %data_len",
            "  store i8 0, ptr %zero_ptr",
            "  ret ptr %out",
            "}",
        )
    )
